-- KANT BIBLE / Supabase schema
-- Supabase SQL Editor에서 한 번 실행하세요.

create table if not exists public.books (
  slug text primary key,
  name_ko text not null,
  testament text not null check (testament in ('OT','NT')),
  created_at timestamptz not null default now()
);

create table if not exists public.lectures (
  id bigint generated by default as identity primary key,
  book_slug text references public.books(slug) on delete cascade,
  title text not null,
  summary text,
  content_html text,
  is_published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lectures_book_slug_idx on public.lectures(book_slug);
create index if not exists lectures_published_updated_idx on public.lectures(is_published, updated_at desc);

alter table public.books enable row level security;
alter table public.lectures enable row level security;

drop policy if exists "Public can read books" on public.books;
create policy "Public can read books"
on public.books for select
to anon, authenticated
using (true);

drop policy if exists "Public can read published lectures" on public.lectures;
create policy "Public can read published lectures"
on public.lectures for select
to anon, authenticated
using (is_published = true);

insert into public.books (slug, name_ko, testament) values
('1-chronicles','역대상','OT'),
('1-corinthians','고린도전서','NT'),
('1-john','요한일서','NT'),
('1-kings','열왕기상','OT'),
('1-peter','베드로전서','NT'),
('1-samuel','사무엘상','OT'),
('1-thessalonians','데살로니가전서','NT'),
('1-timothy','디모데전서','NT'),
('2-chronicles','역대하','OT'),
('2-corinthians','고린도후서','NT'),
('2-john','요한이서','NT'),
('2-kings','열왕기하','OT'),
('2-peter','베드로후서','NT'),
('2-samuel','사무엘하','OT'),
('2-thessalonians','데살로니가후서','NT'),
('2-timothy','디모데후서','NT'),
('3-john','요한삼서','NT'),
('acts','사도행전','NT'),
('amos','아모스','OT'),
('colossians','골로새서','NT'),
('daniel','다니엘','OT'),
('deuteronomy','신명기','OT'),
('ecclesiastes','전도서','OT'),
('ephesians','에베소서','NT'),
('esther','에스더','OT'),
('exodus','출애굽기','OT'),
('ezekiel','에스겔','OT'),
('ezra','에스라','OT'),
('galatians','갈라디아서','NT'),
('genesis','창세기','OT'),
('habakkuk','하박국','OT'),
('haggai','학개','OT'),
('hebrews','히브리서','NT'),
('hosea','호세아','OT'),
('isaiah','이사야','OT'),
('james','야고보서','NT'),
('jeremiah','예레미야','OT'),
('job','욥기','OT'),
('joel','요엘','OT'),
('john','요한복음','NT'),
('jonah','요나','OT'),
('joshua','여호수아','OT'),
('jude','유다서','NT'),
('judges','사사기','OT'),
('lamentations','예레미야애가','OT'),
('leviticus','레위기','OT'),
('luke','누가복음','NT'),
('malachi','말라기','OT'),
('mark','마가복음','NT'),
('matthew','마태복음','NT'),
('micah','미가','OT'),
('nahum','나훔','OT'),
('nehemiah','느헤미야','OT'),
('numbers','민수기','OT'),
('obadiah','오바댜','OT'),
('philemon','빌레몬서','NT'),
('philippians','빌립보서','NT'),
('proverbs','잠언','OT'),
('psalms','시편','OT'),
('revelation','요한계시록','NT'),
('romans','로마서','NT'),
('ruth','룻기','OT'),
('song-of-songs','아가','OT'),
('titus','디도서','NT'),
('zechariah','스가랴','OT'),
('zephaniah','스바냐','OT')
on conflict (slug) do update
set name_ko = excluded.name_ko,
    testament = excluded.testament;

-- 예시 강의안
-- insert into public.lectures (book_slug, title, summary, content_html, is_published)
-- values ('luke', '누가복음 1–4장', '누가복음 서론과 예수의 정체·사명을 다룹니다.',
--         '<h2>강의 내용</h2><p>여기에 HTML 강의안을 넣습니다.</p>', true);
